version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  pgdata:
