services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-service
    restart: on-failure
    depends_on:
      # - user-service
      - promo-service
    ports:
      - "12300:12300"

  statistics-service:
    build:
      context: ./statistics
      dockerfile: Dockerfile
    container_name: statistics-service
    restart: on-failure
    ports:
      - "12300:12300"

  promo-service:
    build:
      context: ./promo
      dockerfile: Dockerfile
    container_name: promo-service
    restart: on-failure
    depends_on:
      - kafka
      - promo-postgres
    ports:
      - "12301:12301"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS="view_promo:1:1,like_promo:1:1,comment_promo:1:1,view_post:1:1,like_post:1:1,comment_post:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics.sh",
          "--bootstrap-server=localhost:9092",
          "--list",
        ]
      start_period: 5s
      interval: 2s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  clickhouse:
    image: yandex/clickhouse-server:21.3
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  pgdata:
  clickhouse_data:
