// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.3
// source: stats.proto

package statspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StatisticsService_GetPromoStats_FullMethodName    = "/statistics.StatisticsService/GetPromoStats"
	StatisticsService_GetPromoDynamics_FullMethodName = "/statistics.StatisticsService/GetPromoDynamics"
	StatisticsService_GetTopPromos_FullMethodName     = "/statistics.StatisticsService/GetTopPromos"
	StatisticsService_GetTopUsers_FullMethodName      = "/statistics.StatisticsService/GetTopUsers"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetPromoStats(ctx context.Context, in *GetPromoStatsRequest, opts ...grpc.CallOption) (*GetPromoStatsResponse, error)
	GetPromoDynamics(ctx context.Context, in *GetPromoDynamicsRequest, opts ...grpc.CallOption) (*GetPromoDynamicsResponse, error)
	GetTopPromos(ctx context.Context, in *GetTopPromosRequest, opts ...grpc.CallOption) (*GetTopPromosResponse, error)
	GetTopUsers(ctx context.Context, in *GetTopUsersRequest, opts ...grpc.CallOption) (*GetTopUsersResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetPromoStats(ctx context.Context, in *GetPromoStatsRequest, opts ...grpc.CallOption) (*GetPromoStatsResponse, error) {
	out := new(GetPromoStatsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPromoStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetPromoDynamics(ctx context.Context, in *GetPromoDynamicsRequest, opts ...grpc.CallOption) (*GetPromoDynamicsResponse, error) {
	out := new(GetPromoDynamicsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetPromoDynamics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTopPromos(ctx context.Context, in *GetTopPromosRequest, opts ...grpc.CallOption) (*GetTopPromosResponse, error) {
	out := new(GetTopPromosResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTopPromos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTopUsers(ctx context.Context, in *GetTopUsersRequest, opts ...grpc.CallOption) (*GetTopUsersResponse, error) {
	out := new(GetTopUsersResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTopUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility
type StatisticsServiceServer interface {
	GetPromoStats(context.Context, *GetPromoStatsRequest) (*GetPromoStatsResponse, error)
	GetPromoDynamics(context.Context, *GetPromoDynamicsRequest) (*GetPromoDynamicsResponse, error)
	GetTopPromos(context.Context, *GetTopPromosRequest) (*GetTopPromosResponse, error)
	GetTopUsers(context.Context, *GetTopUsersRequest) (*GetTopUsersResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticsServiceServer struct {
}

func (UnimplementedStatisticsServiceServer) GetPromoStats(context.Context, *GetPromoStatsRequest) (*GetPromoStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoStats not implemented")
}
func (UnimplementedStatisticsServiceServer) GetPromoDynamics(context.Context, *GetPromoDynamicsRequest) (*GetPromoDynamicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoDynamics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTopPromos(context.Context, *GetTopPromosRequest) (*GetTopPromosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPromos not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTopUsers(context.Context, *GetTopUsersRequest) (*GetTopUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUsers not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetPromoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromoStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPromoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPromoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPromoStats(ctx, req.(*GetPromoStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetPromoDynamics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromoDynamicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPromoDynamics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetPromoDynamics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPromoDynamics(ctx, req.(*GetPromoDynamicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTopPromos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPromosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTopPromos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTopPromos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTopPromos(ctx, req.(*GetTopPromosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTopUsers(ctx, req.(*GetTopUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPromoStats",
			Handler:    _StatisticsService_GetPromoStats_Handler,
		},
		{
			MethodName: "GetPromoDynamics",
			Handler:    _StatisticsService_GetPromoDynamics_Handler,
		},
		{
			MethodName: "GetTopPromos",
			Handler:    _StatisticsService_GetTopPromos_Handler,
		},
		{
			MethodName: "GetTopUsers",
			Handler:    _StatisticsService_GetTopUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats.proto",
}
