// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: stats.proto

package statspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric int32

const (
	Metric_VIEWS    Metric = 0
	Metric_LIKES    Metric = 1
	Metric_COMMENTS Metric = 2
)

// Enum value maps for Metric.
var (
	Metric_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	Metric_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x Metric) Enum() *Metric {
	p := new(Metric)
	*p = x
	return p
}

func (x Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_proto_enumTypes[0].Descriptor()
}

func (Metric) Type() protoreflect.EnumType {
	return &file_stats_proto_enumTypes[0]
}

func (x Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric.Descriptor instead.
func (Metric) EnumDescriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

type GetPromoStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromoId uint64 `protobuf:"varint,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
}

func (x *GetPromoStatsRequest) Reset() {
	*x = GetPromoStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromoStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoStatsRequest) ProtoMessage() {}

func (x *GetPromoStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPromoStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetPromoStatsRequest) GetPromoId() uint64 {
	if x != nil {
		return x.PromoId
	}
	return 0
}

type GetPromoStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Views    uint64 `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Likes    uint64 `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments uint64 `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
}

func (x *GetPromoStatsResponse) Reset() {
	*x = GetPromoStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromoStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoStatsResponse) ProtoMessage() {}

func (x *GetPromoStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPromoStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetPromoStatsResponse) GetViews() uint64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetPromoStatsResponse) GetLikes() uint64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *GetPromoStatsResponse) GetComments() uint64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type GetPromoDynamicsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromoId   uint64                 `protobuf:"varint,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	Metric    Metric                 `protobuf:"varint,2,opt,name=metric,proto3,enum=statistics.Metric" json:"metric,omitempty"`
	StartDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (x *GetPromoDynamicsRequest) Reset() {
	*x = GetPromoDynamicsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromoDynamicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoDynamicsRequest) ProtoMessage() {}

func (x *GetPromoDynamicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoDynamicsRequest.ProtoReflect.Descriptor instead.
func (*GetPromoDynamicsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetPromoDynamicsRequest) GetPromoId() uint64 {
	if x != nil {
		return x.PromoId
	}
	return 0
}

func (x *GetPromoDynamicsRequest) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_VIEWS
}

func (x *GetPromoDynamicsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetPromoDynamicsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetPromoDynamicsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*DynamicsEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GetPromoDynamicsResponse) Reset() {
	*x = GetPromoDynamicsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromoDynamicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoDynamicsResponse) ProtoMessage() {}

func (x *GetPromoDynamicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoDynamicsResponse.ProtoReflect.Descriptor instead.
func (*GetPromoDynamicsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetPromoDynamicsResponse) GetEntries() []*DynamicsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetTopPromosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric Metric `protobuf:"varint,1,opt,name=metric,proto3,enum=statistics.Metric" json:"metric,omitempty"`
}

func (x *GetTopPromosRequest) Reset() {
	*x = GetTopPromosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPromosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPromosRequest) ProtoMessage() {}

func (x *GetTopPromosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPromosRequest.ProtoReflect.Descriptor instead.
func (*GetTopPromosRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopPromosRequest) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_VIEWS
}

type GetTopPromosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopPromos []*TopPromo `protobuf:"bytes,1,rep,name=top_promos,json=topPromos,proto3" json:"top_promos,omitempty"`
}

func (x *GetTopPromosResponse) Reset() {
	*x = GetTopPromosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPromosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPromosResponse) ProtoMessage() {}

func (x *GetTopPromosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPromosResponse.ProtoReflect.Descriptor instead.
func (*GetTopPromosResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopPromosResponse) GetTopPromos() []*TopPromo {
	if x != nil {
		return x.TopPromos
	}
	return nil
}

type GetTopUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric Metric `protobuf:"varint,1,opt,name=metric,proto3,enum=statistics.Metric" json:"metric,omitempty"`
}

func (x *GetTopUsersRequest) Reset() {
	*x = GetTopUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersRequest) ProtoMessage() {}

func (x *GetTopUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersRequest.ProtoReflect.Descriptor instead.
func (*GetTopUsersRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopUsersRequest) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_VIEWS
}

type GetTopUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopUsers []*TopUser `protobuf:"bytes,1,rep,name=top_users,json=topUsers,proto3" json:"top_users,omitempty"`
}

func (x *GetTopUsersResponse) Reset() {
	*x = GetTopUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse) ProtoMessage() {}

func (x *GetTopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopUsersResponse) GetTopUsers() []*TopUser {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

type DynamicsEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DynamicsEntry) Reset() {
	*x = DynamicsEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicsEntry) ProtoMessage() {}

func (x *DynamicsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicsEntry.ProtoReflect.Descriptor instead.
func (*DynamicsEntry) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{8}
}

func (x *DynamicsEntry) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *DynamicsEntry) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopPromo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromoId uint64 `protobuf:"varint,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	Count   uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TopPromo) Reset() {
	*x = TopPromo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopPromo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPromo) ProtoMessage() {}

func (x *TopPromo) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPromo.ProtoReflect.Descriptor instead.
func (*TopPromo) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{9}
}

func (x *TopPromo) GetPromoId() uint64 {
	if x != nil {
		return x.PromoId
	}
	return 0
}

func (x *TopPromo) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count  uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TopUser) Reset() {
	*x = TopUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stats_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUser) ProtoMessage() {}

func (x *TopUser) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUser.ProtoReflect.Descriptor instead.
func (*TopUser) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{10}
}

func (x *TopUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TopUser) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_stats_proto protoreflect.FileDescriptor

var file_stats_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x49, 0x64, 0x22, 0x5f, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6b,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xd2,
	0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x6d, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x6d, 0x6f, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x4b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x70, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x2e, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x73, 0x22, 0x40, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x09, 0x74, 0x6f, 0x70, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x54, 0x6f,
	0x70, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x55, 0x0a, 0x0d, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x08, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x07, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x2c, 0x0a,
	0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x45, 0x57, 0x53,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49, 0x4b, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x53, 0x10, 0x02, 0x32, 0xeb, 0x02, 0x0a, 0x11,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x12, 0x23, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x73, 0x12, 0x1f, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData = file_stats_proto_rawDesc
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_stats_proto_rawDescData)
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stats_proto_goTypes = []interface{}{
	(Metric)(0),                      // 0: statistics.Metric
	(*GetPromoStatsRequest)(nil),     // 1: statistics.GetPromoStatsRequest
	(*GetPromoStatsResponse)(nil),    // 2: statistics.GetPromoStatsResponse
	(*GetPromoDynamicsRequest)(nil),  // 3: statistics.GetPromoDynamicsRequest
	(*GetPromoDynamicsResponse)(nil), // 4: statistics.GetPromoDynamicsResponse
	(*GetTopPromosRequest)(nil),      // 5: statistics.GetTopPromosRequest
	(*GetTopPromosResponse)(nil),     // 6: statistics.GetTopPromosResponse
	(*GetTopUsersRequest)(nil),       // 7: statistics.GetTopUsersRequest
	(*GetTopUsersResponse)(nil),      // 8: statistics.GetTopUsersResponse
	(*DynamicsEntry)(nil),            // 9: statistics.DynamicsEntry
	(*TopPromo)(nil),                 // 10: statistics.TopPromo
	(*TopUser)(nil),                  // 11: statistics.TopUser
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_stats_proto_depIdxs = []int32{
	0,  // 0: statistics.GetPromoDynamicsRequest.metric:type_name -> statistics.Metric
	12, // 1: statistics.GetPromoDynamicsRequest.start_date:type_name -> google.protobuf.Timestamp
	12, // 2: statistics.GetPromoDynamicsRequest.end_date:type_name -> google.protobuf.Timestamp
	9,  // 3: statistics.GetPromoDynamicsResponse.entries:type_name -> statistics.DynamicsEntry
	0,  // 4: statistics.GetTopPromosRequest.metric:type_name -> statistics.Metric
	10, // 5: statistics.GetTopPromosResponse.top_promos:type_name -> statistics.TopPromo
	0,  // 6: statistics.GetTopUsersRequest.metric:type_name -> statistics.Metric
	11, // 7: statistics.GetTopUsersResponse.top_users:type_name -> statistics.TopUser
	12, // 8: statistics.DynamicsEntry.date:type_name -> google.protobuf.Timestamp
	1,  // 9: statistics.StatisticsService.GetPromoStats:input_type -> statistics.GetPromoStatsRequest
	3,  // 10: statistics.StatisticsService.GetPromoDynamics:input_type -> statistics.GetPromoDynamicsRequest
	5,  // 11: statistics.StatisticsService.GetTopPromos:input_type -> statistics.GetTopPromosRequest
	7,  // 12: statistics.StatisticsService.GetTopUsers:input_type -> statistics.GetTopUsersRequest
	2,  // 13: statistics.StatisticsService.GetPromoStats:output_type -> statistics.GetPromoStatsResponse
	4,  // 14: statistics.StatisticsService.GetPromoDynamics:output_type -> statistics.GetPromoDynamicsResponse
	6,  // 15: statistics.StatisticsService.GetTopPromos:output_type -> statistics.GetTopPromosResponse
	8,  // 16: statistics.StatisticsService.GetTopUsers:output_type -> statistics.GetTopUsersResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromoStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromoStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromoDynamicsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromoDynamicsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPromosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPromosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicsEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopPromo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stats_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stats_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		EnumInfos:         file_stats_proto_enumTypes,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_rawDesc = nil
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
