// Code generated by ogen, DO NOT EDIT.

package api_desc

import (
	"time"
)

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// GetUserProfileInternalServerError is response for GetUserProfile operation.
type GetUserProfileInternalServerError struct{}

func (*GetUserProfileInternalServerError) getUserProfileRes() {}

type GetUserProfileOK struct {
	Login     OptString `json:"login"`
	Email     OptString `json:"email"`
	FirstName OptString `json:"first_name"`
	LastName  OptString `json:"last_name"`
	BirthDate OptDate   `json:"birth_date"`
	Phone     OptString `json:"phone"`
}

// GetLogin returns the value of Login.
func (s *GetUserProfileOK) GetLogin() OptString {
	return s.Login
}

// GetEmail returns the value of Email.
func (s *GetUserProfileOK) GetEmail() OptString {
	return s.Email
}

// GetFirstName returns the value of FirstName.
func (s *GetUserProfileOK) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *GetUserProfileOK) GetLastName() OptString {
	return s.LastName
}

// GetBirthDate returns the value of BirthDate.
func (s *GetUserProfileOK) GetBirthDate() OptDate {
	return s.BirthDate
}

// GetPhone returns the value of Phone.
func (s *GetUserProfileOK) GetPhone() OptString {
	return s.Phone
}

// SetLogin sets the value of Login.
func (s *GetUserProfileOK) SetLogin(val OptString) {
	s.Login = val
}

// SetEmail sets the value of Email.
func (s *GetUserProfileOK) SetEmail(val OptString) {
	s.Email = val
}

// SetFirstName sets the value of FirstName.
func (s *GetUserProfileOK) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *GetUserProfileOK) SetLastName(val OptString) {
	s.LastName = val
}

// SetBirthDate sets the value of BirthDate.
func (s *GetUserProfileOK) SetBirthDate(val OptDate) {
	s.BirthDate = val
}

// SetPhone sets the value of Phone.
func (s *GetUserProfileOK) SetPhone(val OptString) {
	s.Phone = val
}

func (*GetUserProfileOK) getUserProfileRes() {}

// GetUserProfileUnauthorized is response for GetUserProfile operation.
type GetUserProfileUnauthorized struct{}

func (*GetUserProfileUnauthorized) getUserProfileRes() {}

// LoginUserInternalServerError is response for LoginUser operation.
type LoginUserInternalServerError struct{}

func (*LoginUserInternalServerError) loginUserRes() {}

type LoginUserOK struct {
	Token OptString `json:"token"`
}

// GetToken returns the value of Token.
func (s *LoginUserOK) GetToken() OptString {
	return s.Token
}

// SetToken sets the value of Token.
func (s *LoginUserOK) SetToken(val OptString) {
	s.Token = val
}

func (*LoginUserOK) loginUserRes() {}

type LoginUserReq struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetLogin returns the value of Login.
func (s *LoginUserReq) GetLogin() string {
	return s.Login
}

// GetPassword returns the value of Password.
func (s *LoginUserReq) GetPassword() string {
	return s.Password
}

// SetLogin sets the value of Login.
func (s *LoginUserReq) SetLogin(val string) {
	s.Login = val
}

// SetPassword sets the value of Password.
func (s *LoginUserReq) SetPassword(val string) {
	s.Password = val
}

// LoginUserUnauthorized is response for LoginUser operation.
type LoginUserUnauthorized struct{}

func (*LoginUserUnauthorized) loginUserRes() {}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RegisterUserBadRequest is response for RegisterUser operation.
type RegisterUserBadRequest struct{}

func (*RegisterUserBadRequest) registerUserRes() {}

// RegisterUserInternalServerError is response for RegisterUser operation.
type RegisterUserInternalServerError struct{}

func (*RegisterUserInternalServerError) registerUserRes() {}

// RegisterUserOK is response for RegisterUser operation.
type RegisterUserOK struct{}

func (*RegisterUserOK) registerUserRes() {}

type RegisterUserReq struct {
	Login    string `json:"login"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

// GetLogin returns the value of Login.
func (s *RegisterUserReq) GetLogin() string {
	return s.Login
}

// GetPassword returns the value of Password.
func (s *RegisterUserReq) GetPassword() string {
	return s.Password
}

// GetEmail returns the value of Email.
func (s *RegisterUserReq) GetEmail() string {
	return s.Email
}

// SetLogin sets the value of Login.
func (s *RegisterUserReq) SetLogin(val string) {
	s.Login = val
}

// SetPassword sets the value of Password.
func (s *RegisterUserReq) SetPassword(val string) {
	s.Password = val
}

// SetEmail sets the value of Email.
func (s *RegisterUserReq) SetEmail(val string) {
	s.Email = val
}

// UpdateUserProfileBadRequest is response for UpdateUserProfile operation.
type UpdateUserProfileBadRequest struct{}

func (*UpdateUserProfileBadRequest) updateUserProfileRes() {}

// UpdateUserProfileInternalServerError is response for UpdateUserProfile operation.
type UpdateUserProfileInternalServerError struct{}

func (*UpdateUserProfileInternalServerError) updateUserProfileRes() {}

// UpdateUserProfileOK is response for UpdateUserProfile operation.
type UpdateUserProfileOK struct{}

func (*UpdateUserProfileOK) updateUserProfileRes() {}

type UpdateUserProfileReq struct {
	FirstName OptString `json:"first_name"`
	LastName  OptString `json:"last_name"`
	BirthDate OptDate   `json:"birth_date"`
	Email     OptString `json:"email"`
	Phone     OptString `json:"phone"`
}

// GetFirstName returns the value of FirstName.
func (s *UpdateUserProfileReq) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *UpdateUserProfileReq) GetLastName() OptString {
	return s.LastName
}

// GetBirthDate returns the value of BirthDate.
func (s *UpdateUserProfileReq) GetBirthDate() OptDate {
	return s.BirthDate
}

// GetEmail returns the value of Email.
func (s *UpdateUserProfileReq) GetEmail() OptString {
	return s.Email
}

// GetPhone returns the value of Phone.
func (s *UpdateUserProfileReq) GetPhone() OptString {
	return s.Phone
}

// SetFirstName sets the value of FirstName.
func (s *UpdateUserProfileReq) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *UpdateUserProfileReq) SetLastName(val OptString) {
	s.LastName = val
}

// SetBirthDate sets the value of BirthDate.
func (s *UpdateUserProfileReq) SetBirthDate(val OptDate) {
	s.BirthDate = val
}

// SetEmail sets the value of Email.
func (s *UpdateUserProfileReq) SetEmail(val OptString) {
	s.Email = val
}

// SetPhone sets the value of Phone.
func (s *UpdateUserProfileReq) SetPhone(val OptString) {
	s.Phone = val
}

// UpdateUserProfileUnauthorized is response for UpdateUserProfile operation.
type UpdateUserProfileUnauthorized struct{}

func (*UpdateUserProfileUnauthorized) updateUserProfileRes() {}
