// Code generated by ogen, DO NOT EDIT.

package api_desc

// OperationName is the ogen operation name
type OperationName = string

const (
	GetUserProfileOperation    OperationName = "GetUserProfile"
	LoginUserOperation         OperationName = "LoginUser"
	RegisterUserOperation      OperationName = "RegisterUser"
	UpdateUserProfileOperation OperationName = "UpdateUserProfile"
)
