// Code generated by ogen, DO NOT EDIT.

package api_desc

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetUserProfile implements getUserProfile operation.
//
// Получение данных профиля.
//
// GET /profile
func (UnimplementedHandler) GetUserProfile(ctx context.Context) (r GetUserProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginUser implements loginUser operation.
//
// Аутентификация пользователя.
//
// POST /login
func (UnimplementedHandler) LoginUser(ctx context.Context, req *LoginUserReq) (r LoginUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements registerUser operation.
//
// Регистрация нового пользователя.
//
// POST /register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterUserReq) (r RegisterUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserProfile implements updateUserProfile operation.
//
// Обновление профиля пользователя.
//
// PUT /profile
func (UnimplementedHandler) UpdateUserProfile(ctx context.Context, req *UpdateUserProfileReq) (r UpdateUserProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}
