// Code generated by ogen, DO NOT EDIT.
package api_desc

type GetUserProfileRes interface {
	getUserProfileRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type RegisterUserRes interface {
	registerUserRes()
}

type UpdateUserProfileRes interface {
	updateUserProfileRes()
}
