// Code generated by ogen, DO NOT EDIT.

package api_desc

// OperationName is the ogen operation name
type OperationName = string

const (
	ClickPromoOperation     OperationName = "ClickPromo"
	CommentPromoOperation   OperationName = "CommentPromo"
	ListCommentsOperation   OperationName = "ListComments"
	RegisterClientOperation OperationName = "RegisterClient"
	ViewPromoOperation      OperationName = "ViewPromo"
)
