// Code generated by ogen, DO NOT EDIT.
package api_desc

type ClickPromoRes interface {
	clickPromoRes()
}

type CommentPromoRes interface {
	commentPromoRes()
}

type ListCommentsRes interface {
	listCommentsRes()
}

type RegisterClientRes interface {
	registerClientRes()
}

type ViewPromoRes interface {
	viewPromoRes()
}
