// Code generated by ogen, DO NOT EDIT.

package api_desc

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ClickPromo implements ClickPromo operation.
//
// Record a promo click.
//
// POST /promos/clicks
func (UnimplementedHandler) ClickPromo(ctx context.Context, req *ClickPromoReq) (r ClickPromoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CommentPromo implements CommentPromo operation.
//
// Add a comment to a promo.
//
// POST /promos/comments
func (UnimplementedHandler) CommentPromo(ctx context.Context, req *CommentPromoReq) (r CommentPromoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListComments implements ListComments operation.
//
// List comments for a promo.
//
// GET /promos/{entity_id}/comments
func (UnimplementedHandler) ListComments(ctx context.Context, params ListCommentsParams) (r ListCommentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterClient implements RegisterClient operation.
//
// Register a new client.
//
// POST /clients
func (UnimplementedHandler) RegisterClient(ctx context.Context, req *RegisterClientReq) (r RegisterClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ViewPromo implements ViewPromo operation.
//
// Record a promo view.
//
// POST /promos/views
func (UnimplementedHandler) ViewPromo(ctx context.Context, req *ViewPromoReq) (r ViewPromoRes, _ error) {
	return r, ht.ErrNotImplemented
}
